### ISSUE TITLE
contains duplicate operationId

### ISSUE THREAD

**Issue by Penberthy** [ge-flight-analytics/EmsApi.Client#11]
when you validate the swagger spec  
https://github.com/ge-flight-analytics/EmsApi.Client/blob/master/EmsApi.Dto/ems-api.json
you get the following errors

The swagger spec at "ems-api.json" is invalid against swagger specification 2.0.
See errors below:
- "Analytic_GetAnalyticGroupContents" is defined 2 times
- "Asset_GetAircraft" is defined 2 times
- "Analytic_GetAnalyticInfo" is defined 2 times
- "Analytic_SearchForAnalytics" is defined 2 times
- "Transfer_GetUploadProcessingStatus" is defined 2 times

According to the swagger specification operationId "The id MUST be unique among all operations described in the API"
https://swagger.io/specification/

**Comment by c-owens** [comment]
This is fixed for the upcoming 1.1.0 release and in the back end API that generates it. In the meantime you can either use the version from the `dotnetcore` branch or in the `ems-api-sdk` project here: https://github.com/ge-flight-analytics/ems-api-sdk/blob/master/ems-api.json
